Adding tutorial for package binary
haskell-lang/haskell-lang pull request #120
Opened 2017-02-22 12:44 UTC by eeoam

2017-02-22 17:05 UTC, snoyberg commented
Just to be clear, the current content is simply "dummy." I'm assuming additional content was intended?

2017-02-24 17:31 UTC, eeoam commented
Absolutely. The tutorial is now ready for review.

2017-02-26 12:32 UTC, snoyberg requested changes

2017-02-26 12:32 UTC, snoyberg commented on static/tutorial/package-binary.md
> +<i>binary</i> is straightforward to use library for decoding (parsing)
Markdown note: you can represent this as `*binary*` instead of HTML tags.

2017-02-26 12:32 UTC, snoyberg commented on static/tutorial/package-binary.md
> +> encode True
This should be enclosed in something like:

    ```
    > encode True
    ```

2017-02-26 12:32 UTC, snoyberg commented on static/tutorial/package-binary.md
> +So how do you define`Binary` instances for types that do not already have them?
Missing space after `define`

2017-02-26 12:32 UTC, snoyberg commented on static/tutorial/package-binary.md
> +```haskell
Better to have an empty line above this.

2017-02-26 12:32 UTC, snoyberg commented on static/tutorial/package-binary.md
> +-- stack --install-ghc --resolver lts-7.4 runghc BinaryCustom
I think this should be:

```
#!/usr/bin/env stack
-- stack --install-ghc --resolver lts-7.4 runghc
```

2017-02-26 12:32 UTC, snoyberg commented on static/tutorial/package-binary.md
> +While quite straightforward to use, the <i>binary</i> library vulnerable
s/`library vulnerable`/`library is vulnerable`

2017-02-27 10:24 UTC, eeoam commented
I have incorporated the changes.

2017-02-27 13:26 UTC, snoyberg commented on static/tutorial/package-binary.md
>  -- stack --install-ghc --resolver lts-7.4 runghc BinaryGeneric.hs
The presence of the filename here will cause problems.

2017-02-27 13:26 UTC, snoyberg commented on static/tutorial/package-binary.md
>  -- stack --install-ghc --resolver lts-7.4 runghc BinaryCustom
`BinaryCustom` should be removed here too.

2017-02-27 13:42 UTC, snoyberg approved these changes

2017-02-27 13:42 UTC, merged

2017-02-27 13:42 UTC, snoyberg commented
Thanks!